# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConkyLuaMakerPyQt5.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DesignerTab = QtWidgets.QTabWidget(self.centralwidget)
        self.DesignerTab.setObjectName("DesignerTab")
        self.Designer = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Designer.sizePolicy().hasHeightForWidth())
        self.Designer.setSizePolicy(sizePolicy)
        self.Designer.setObjectName("Designer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Designer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_6 = QtWidgets.QWidget(self.Designer)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget_6)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ellipsegraphBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipsegraphBtn.sizePolicy().hasHeightForWidth())
        self.ellipsegraphBtn.setSizePolicy(sizePolicy)
        self.ellipsegraphBtn.setMaximumSize(QtCore.QSize(197, 16777215))
        self.ellipsegraphBtn.setObjectName("ellipsegraphBtn")
        self.verticalLayout_5.addWidget(self.ellipsegraphBtn)
        self.ringgraphBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ringgraphBtn.sizePolicy().hasHeightForWidth())
        self.ringgraphBtn.setSizePolicy(sizePolicy)
        self.ringgraphBtn.setMaximumSize(QtCore.QSize(197, 16777215))
        self.ringgraphBtn.setObjectName("ringgraphBtn")
        self.verticalLayout_5.addWidget(self.ringgraphBtn)
        self.bargraphBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bargraphBtn.sizePolicy().hasHeightForWidth())
        self.bargraphBtn.setSizePolicy(sizePolicy)
        self.bargraphBtn.setMaximumSize(QtCore.QSize(197, 16777215))
        self.bargraphBtn.setObjectName("bargraphBtn")
        self.verticalLayout_5.addWidget(self.bargraphBtn)
        self.vartextBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vartextBtn.sizePolicy().hasHeightForWidth())
        self.vartextBtn.setSizePolicy(sizePolicy)
        self.vartextBtn.setMaximumSize(QtCore.QSize(197, 16777215))
        self.vartextBtn.setObjectName("vartextBtn")
        self.verticalLayout_5.addWidget(self.vartextBtn)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_6)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ringBtn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ringBtn.sizePolicy().hasHeightForWidth())
        self.ringBtn.setSizePolicy(sizePolicy)
        self.ringBtn.setMaximumSize(QtCore.QSize(197, 16777215))
        self.ringBtn.setObjectName("ringBtn")
        self.verticalLayout_6.addWidget(self.ringBtn)
        self.ellipseBtn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipseBtn.sizePolicy().hasHeightForWidth())
        self.ellipseBtn.setSizePolicy(sizePolicy)
        self.ellipseBtn.setMaximumSize(QtCore.QSize(197, 16777215))
        self.ellipseBtn.setObjectName("ellipseBtn")
        self.verticalLayout_6.addWidget(self.ellipseBtn)
        self.statextBtn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statextBtn.sizePolicy().hasHeightForWidth())
        self.statextBtn.setSizePolicy(sizePolicy)
        self.statextBtn.setMaximumSize(QtCore.QSize(197, 16777215))
        self.statextBtn.setObjectName("statextBtn")
        self.verticalLayout_6.addWidget(self.statextBtn)
        self.lineBtn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineBtn.sizePolicy().hasHeightForWidth())
        self.lineBtn.setSizePolicy(sizePolicy)
        self.lineBtn.setMaximumSize(QtCore.QSize(197, 16777215))
        self.lineBtn.setObjectName("lineBtn")
        self.verticalLayout_6.addWidget(self.lineBtn)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout.addWidget(self.widget_6)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.previewgraphicview = PreviewGraphicScene(self.Designer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewgraphicview.sizePolicy().hasHeightForWidth())
        self.previewgraphicview.setSizePolicy(sizePolicy)
        self.previewgraphicview.setMinimumSize(QtCore.QSize(200, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.previewgraphicview.setPalette(palette)
        self.previewgraphicview.setObjectName("previewgraphicview")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.previewgraphicview)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3.addWidget(self.previewgraphicview, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.widget = QtWidgets.QWidget(self.Designer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.MousePosLabel = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MousePosLabel.sizePolicy().hasHeightForWidth())
        self.MousePosLabel.setSizePolicy(sizePolicy)
        self.MousePosLabel.setObjectName("MousePosLabel")
        self.gridLayout.addWidget(self.MousePosLabel, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridsizeSpinBox = QtWidgets.QSpinBox(self.widget_2)
        self.gridsizeSpinBox.setObjectName("gridsizeSpinBox")
        self.gridLayout.addWidget(self.gridsizeSpinBox, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 2, 1, 1)
        self.gridsizeslider = QtWidgets.QSlider(self.widget_2)
        self.gridsizeslider.setOrientation(QtCore.Qt.Horizontal)
        self.gridsizeslider.setObjectName("gridsizeslider")
        self.gridLayout.addWidget(self.gridsizeslider, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget_2)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.Properties_2 = QtWidgets.QWidget(self.Designer)
        self.Properties_2.setMinimumSize(QtCore.QSize(100, 0))
        self.Properties_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.Properties_2.setObjectName("Properties_2")
        self.Properties = QtWidgets.QVBoxLayout(self.Properties_2)
        self.Properties.setObjectName("Properties")
        self.widget_3 = QtWidgets.QWidget(self.Properties_2)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 222, 134))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ObjectList = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.ObjectList.setObjectName("ObjectList")
        self.horizontalLayout_4.addWidget(self.ObjectList)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.Properties.addWidget(self.widget_3)
        self.widget_9 = QtWidgets.QWidget(self.Properties_2)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DeleteBtn = QtWidgets.QPushButton(self.widget_9)
        self.DeleteBtn.setObjectName("DeleteBtn")
        self.horizontalLayout_3.addWidget(self.DeleteBtn)
        self.RenameBtn = QtWidgets.QPushButton(self.widget_9)
        self.RenameBtn.setObjectName("RenameBtn")
        self.horizontalLayout_3.addWidget(self.RenameBtn)
        self.Properties.addWidget(self.widget_9)
        self.widget_4 = QtWidgets.QWidget(self.Properties_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PropList = QtWidgets.QTableWidget(self.widget_4)
        self.PropList.setObjectName("PropList")
        self.PropList.setColumnCount(0)
        self.PropList.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.PropList)
        self.Properties.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.Properties_2)
        self.DesignerTab.addTab(self.Designer, "")
        self.Aliases = QtWidgets.QWidget()
        self.Aliases.setObjectName("Aliases")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Aliases)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableView_2 = QtWidgets.QTableView(self.Aliases)
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout_2.addWidget(self.tableView_2, 0, 0, 1, 1)
        self.DesignerTab.addTab(self.Aliases, "")
        self.Conkyproperties = QtWidgets.QWidget()
        self.Conkyproperties.setObjectName("Conkyproperties")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Conkyproperties)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableView_3 = QtWidgets.QTableView(self.Conkyproperties)
        self.tableView_3.setObjectName("tableView_3")
        self.horizontalLayout_6.addWidget(self.tableView_3)
        self.DesignerTab.addTab(self.Conkyproperties, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget_7 = QtWidgets.QWidget(self.tab)
        self.widget_7.setGeometry(QtCore.QRect(180, 80, 120, 80))
        self.widget_7.setObjectName("widget_7")
        self.widget_8 = QtWidgets.QWidget(self.tab)
        self.widget_8.setGeometry(QtCore.QRect(410, 140, 120, 80))
        self.widget_8.setObjectName("widget_8")
        self.DesignerTab.addTab(self.tab, "")
        self.horizontalLayout_2.addWidget(self.DesignerTab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 30))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLOad = QtWidgets.QAction(MainWindow)
        self.actionLOad.setObjectName("actionLOad")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad_background_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_background_Image.setObjectName("actionLoad_background_Image")
        self.menuFichier.addAction(self.actionLOad)
        self.menuFichier.addAction(self.actionSave_as)
        self.menuFichier.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionLoad_background_Image)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.DesignerTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Monitors"))
        self.ellipsegraphBtn.setToolTip(_translate("MainWindow", "Draw an Elliptic monitor"))
        self.ellipsegraphBtn.setText(_translate("MainWindow", "Ellipse Graph"))
        self.ringgraphBtn.setText(_translate("MainWindow", "Ring Graph"))
        self.bargraphBtn.setText(_translate("MainWindow", "Bar Graph"))
        self.vartextBtn.setText(_translate("MainWindow", "Variable Text"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Static"))
        self.ringBtn.setText(_translate("MainWindow", "Ring"))
        self.ellipseBtn.setText(_translate("MainWindow", "Ellipe"))
        self.statextBtn.setText(_translate("MainWindow", "Static Text"))
        self.lineBtn.setText(_translate("MainWindow", "Line"))
        self.MousePosLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Mouse position"))
        self.label.setText(_translate("MainWindow", "Grid size"))
        self.DeleteBtn.setText(_translate("MainWindow", "Delete"))
        self.RenameBtn.setText(_translate("MainWindow", "Rename"))
        self.DesignerTab.setTabText(self.DesignerTab.indexOf(self.Designer), _translate("MainWindow", "Designer"))
        self.DesignerTab.setTabText(self.DesignerTab.indexOf(self.Aliases), _translate("MainWindow", "Aliases"))
        self.DesignerTab.setTabText(self.DesignerTab.indexOf(self.Conkyproperties), _translate("MainWindow", "Global Properties"))
        self.DesignerTab.setTabText(self.DesignerTab.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.menuFichier.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLOad.setText(_translate("MainWindow", "Load"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad_background_Image.setText(_translate("MainWindow", "Load background Image"))
from previewgraphicscene import PreviewGraphicScene
